export const localLangOptions = [
  { label: "English", value: "eng" },
  { label: "Luganda", value: "lug" },
  { label: "Acholi", value: "ach" },
  { label: "Lugbara", value: "lgg" },
  { label: "Runyankole", value: "nyn" },
  { label: "Swahili", value: "swa" },
  { label: "Ateso", value: "teo" },
  { label: "Lusoga", value: "xog" },
  { label: "Rutooro", value: "ttj" },
  { label: "Kinyarwanda", value: "kin" },
  { label: "Lumasaba", value: "myx" },
  { label: "Jopadhola", value: "adh" },
  { label: "Alur", value: "alz" },
  { label: "Bari", value: "bfa" },
  { label: "Rukiga", value: "cgg" },
  { label: "Lugwere", value: "gwr" },
  { label: "Ik", value: "ikx" },
  { label: "Kumam", value: "kdi" },
  { label: "Karamojong", value: "kdj" },
  { label: "Kakwa", value: "keo" },
  { label: "Rukonjo", value: "koo" },
  { label: "Kupsabiny", value: "kpz" },
  { label: "Lango", value: "laj" },
  { label: "Samia", value: "lsm" },
  { label: "Thur", value: "lth" },
  { label: "Aringa", value: "luc" },
  { label: "Ma'di", value: "mhi" },
  { label: "Lugungu", value: "rub" },
  { label: "Ruruuli", value: "ruc" },
  { label: "Kwamba", value: "rwm" },
  { label: "Sebei", value: "sbx" },
  { label: "So", value: "soc" },
  { label: "Bwisi-Talinga", value: "tlj" },
  { label: "Lunyole", value: "nuj" },
  { label: "Runyoro", value: "nyo" },
  { label: "Luo", value: "luo" },
  // {label: "Lendu", value: "led"},
  // {label: "Lulubo", value: "lzm"},
  //{label: "Ndo", value: "ndp"},
  //{label: "Pokot", value: "pok"},
];
