name: Run Cypress Tests
on:
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm i

      - name: Build app
        run: CI=false npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        timeout-minutes: 5

        with:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          VITE_SB_API_URL: ${{ secrets.VITE_SB_API_URL }}
          VITE_SB_API_TOKEN: ${{ secrets.VITE_SB_API_TOKEN }}
          VITE_GA4_TRACKING_ID: ${{ secrets.VITE_GA4_TRACKING_ID }}
          VITE_GA4_MEASUREMENT_ID: ${{ secrets.VITE_GA4_MEASUREMENT_ID }}
          VITE_FEEDBACK_URL: ${{ secrets.VITE_FEEDBACK_URL }}
