name: Build-and-Deploy

on:
  workflow_run:
    workflows: ["Run Cypress Tests"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: npm i

      - name: Build
        env:
          REACT_APP_SB_API_URL: ${{ secrets.REACT_APP_SB_API_URL }}
          REACT_APP_SB_API_TOKEN: ${{ secrets.REACT_APP_SB_API_TOKEN }}
          REACT_APP_GA4_TRACKING_ID: ${{ secrets.REACT_APP_GA4_TRACKING_ID }}
          REACT_APP_GA4_MEASUREMENT_ID: ${{ secrets.REACT_APP_GA4_MEASUREMENT_ID }}
          REACT_APP_FEEDBACK_URL: ${{ secrets.REACT_APP_FEEDBACK_URL }}
        run: CI=false npm run build

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
