name: Build-and-Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: npm i

      - name: Build
        env:
          VITE_SB_API_URL: ${{ secrets.VITE_SB_API_URL }}
          VITE_SB_API_TOKEN: ${{ secrets.VITE_SB_API_TOKEN }}
          VITE_GA4_TRACKING_ID: ${{ secrets.VITE_GA4_TRACKING_ID }}
          VITE_GA4_MEASUREMENT_ID: ${{ secrets.VITE_GA4_MEASUREMENT_ID }}
          VITE_FEEDBACK_URL: ${{ secrets.VITE_FEEDBACK_URL }}
        run: CI=false npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
